# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c78b35c7efe834ee3a6e8531e9452b8f4e5c8c0481f36ff034ad2293fc169b7b83b09e512ce3da0f4fc563f8d1caad3dd990f54a62a8baa44f85ec2d2fbbd282

test:
  secret_key_base: 446f92b50e14c9afc35677bbb215affab85e29886f8a19e132b10ca46f43986018f0d99e7a1c42b6c51e817a64c4bbc42d141d3d12889624c5e30ddfcd1333e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
